name: TypeScript Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Build
        run: npm run build
